### PR TITLE
Bump build number to ensure the latest package gets installed

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
Hopefully fixes the package failing to upload from #27

**Comment by ColCarroll** [comment]
thanks for tracking this down, and sorry for the trouble -- is there an easy repro to check that the requested version works? (i'm suddenly nervous i broke arviz the week of scipy!)

**Comment by dhirschfeld** [comment]
> *is there an easy repro to check that the requested version works?*

The current `arviz=0.12.1-*_0` works and can be installed, it's just that the version from #27 was never uploaded to the [`conda-forge` channel](https://anaconda.org/conda-forge/arviz/files). I found that out by `mamba` still wanting to downgrade my dependencies which relied on `typing_extensions>=4`.

Maybe not uploading the package was an intermittent bug in the `conda-forge` automation, but since this package has uploaded I suspect it just doesn't upload new packages with the same version and build number:

image

Even though the package has been uploaded we'll (usually) have to wait an hour or so for the CDN to sync so it becomes available for install.

I can't see that there would be any problem with the new package as it just removes a pin. If there is a problem, users can always explicitly install the current version with:
```
mamba install arviz=0.12.1=pyhd8ed1ab_0
```

**Comment by ColCarroll** [comment]
:raised_hands: thanks for the very complete answer, and for the PRs!

**Comment by dhirschfeld** [comment]
`arviz=0.12.1-*_1` is now available and looks the same, barring the relaxed `typing_extension` dep so users shouldn't notice any difference other than now being able to install it into environments with the latest `typing_extensions` package:
```
mamba search --info arviz=0.12.1
```
<table>
<tr>
<td>

```
arviz 0.12.1 pyhd8ed1ab_0
-------------------------
file name   : arviz-0.12.1-pyhd8ed1ab_0.tar.bz2
name        : arviz
version     : 0.12.1
build       : pyhd8ed1ab_0
build number: 0
size        : 1.4 MB
license     : Apache-2.0
subdir      : noarch
md5         : fb72aa882035d7373a3c252a937ce6a4
timestamp   : 2022-05-17 03:43:41 UTC
dependencies:
  - matplotlib-base >=3.0
  - netcdf4
  - numpy >=1.12
  - packaging
  - pandas >=0.23
  - python >=3
  - scipy >=0.19
  - setuptools >=38.4
  - typing_extensions >=3.7.4.3,<4
  - xarray >=0.16.1
  - xarray-einstats >=0.2
```
</td>
<td>

```
arviz 0.12.1 pyhd8ed1ab_1
-------------------------
file name   : arviz-0.12.1-pyhd8ed1ab_1.tar.bz2
name        : arviz
version     : 0.12.1
build       : pyhd8ed1ab_1
build number: 1
size        : 1.4 MB
license     : Apache-2.0
subdir      : noarch
md5         : e5d153cbc23cb6144b78022587422c45
timestamp   : 2022-07-13 00:48:25 UTC
dependencies:
  - matplotlib-base >=3.0
  - netcdf4
  - numpy >=1.12
  - packaging
  - pandas >=0.23
  - python >=3
  - scipy >=0.19
  - setuptools >=38.4
  - typing_extensions >=3.7.4.3
  - xarray >=0.16.1
  - xarray-einstats >=0.2
```
</td>
</tr>
</table>

**Comment by canyon289** [comment]
Thank you both

**Pull request merged**
