### PR TITLE
Depend on matplotlib-base to avoid pyqt dependency

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
For more info, see [this comment](https://github.com/jupyter/docker-stacks/pull/896#issuecomment-515888808).

**Comment by ahartikainen** [comment]
Does this affect our 'backend change' hack?

@OriolAbril

If it does, we should add suitable checks and then create a new release.

**Comment by OriolAbril** [comment]
> Does this affect our 'backend change' hack?

It clearly should not. The backend change context manager relies on ipython to do all the hard work, and it can change ipython's inline backend to any matplotlib interactive backend. 

It generally uses Qt backend as the default because this is what ipython does, but it checks if it is available and if it is not it falls back to gtk or tk.

**Comment by ColCarroll** [comment]
This looks good to me, then -- thanks @maresb!

**Review by ahartikainen — APPROVED** [review]

**Pull request merged**
